eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8700/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
server:
  port: 9001
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: main
          search-paths: config
          uri: https://github.com/NiuErQiang/project.git
          

jt:
  dev: 100
